SKILLS = {
    "🐍 Core Python": {
        "badge": "b-core",
        "id": "core",
        "playlists": [
            {
                "title": "Python Tutorials – Data Science & Web Dev",
                "channel": "Corey Schafer",
                "desc": "Gold standard Python tutorials — OOP, Pandas, Matplotlib, Generators. Clear, structured, real examples.",
                "dur": "~20 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU",
            },
            {
                "title": "Python for Beginners – Full Course",
                "channel": "freeCodeCamp",
                "desc": "4.5-hour comprehensive Python beginner course. Best single video to refresh fundamentals fast.",
                "dur": "4.5 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=rfscVS0vtbw",
            },
            {
                "title": "Data Analysis with Python & Pandas",
                "channel": "Data School (Kevin Markham)",
                "desc": "Best pandas playlist on YouTube. Practical real-world data manipulation, cleaning, merging.",
                "dur": "~8 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/playlist?list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y",
            },
            {
                "title": "Python Data Science Full Course",
                "channel": "Codebasics (Dhaval Patel)",
                "desc": "108-video Indian educator playlist. Covers Python + ML + Stats. Highly recommended for Indian fresher context.",
                "dur": "~30 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLeo1K3hjS3us_ELKYSj_Fth2tIEkdKXvV",
            },
        ],
    },
    "🗄️ SQL / Database": {
        "badge": "b-db",
        "id": "db",
        "playlists": [
            {
                "title": "Data Analyst Bootcamp – SQL Complete",
                "channel": "Alex the Analyst",
                "desc": "The #1 DA bootcamp. Covers SQL basics → intermediate → advanced → portfolio projects in one 20-hr playlist.",
                "dur": "~20 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLUaB-1hjhk8FE_XZ87vPPSfHqb6OcM0cF",
            },
            {
                "title": "SQL Tutorial – Full Database Course",
                "channel": "freeCodeCamp",
                "desc": "4-hour complete relational DB + SQL fundamentals. MySQL focused. Great for interview prep.",
                "dur": "4 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
            },
            {
                "title": "Advanced SQL Tutorials (CTEs, Temp Tables, Stored Procs)",
                "channel": "Alex the Analyst",
                "desc": "Short focused videos on advanced SQL concepts tested in DA interviews.",
                "dur": "~2 hrs",
                "level": "Advanced",
                "link": "https://www.youtube.com/playlist?list=PLUaB-1hjhk8EBZNL4nx4Otoa5guqkep_n",
            },
            {
                "title": "MySQL Tutorial for Beginners",
                "channel": "Programming with Mosh",
                "desc": "Professional quality 3-hr MySQL complete tutorial. Covers all fundamentals + joins + stored procedures.",
                "dur": "3 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=7S_tz1z_5bA",
            },
        ],
    },
    "🤖 ML / Scikit-Learn": {
        "badge": "b-ml",
        "id": "ml",
        "playlists": [
            {
                "title": "Scikit-Learn Tutorial – ML in Python",
                "channel": "Data School (Kevin Markham)",
                "desc": "Best scikit-learn playlist. Covers entire ML workflow: preprocessing, modeling, evaluation, pipelines.",
                "dur": "~10 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/playlist?list=PL5-da3qGB5ICeMbQuqys6Us_2i-QbHOgA",
            },
            {
                "title": "Machine Learning with Python – Complete Course",
                "channel": "Codebasics",
                "desc": "End-to-end ML course with Indian-context examples. Linear/logistic regression, trees, SVM, clustering.",
                "dur": "~25 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw",
            },
            {
                "title": "StatQuest: Machine Learning Fundamentals",
                "channel": "StatQuest (Josh Starmer)",
                "desc": "ESSENTIAL. Explains WHY algorithms work — decision trees, random forests, SVM, PCA, bias-variance. Highly visual.",
                "dur": "~15 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF",
            },
            {
                "title": "ML Full Course – freeCodeCamp",
                "channel": "freeCodeCamp",
                "desc": "Multiple full-length ML courses covering linear regression to neural nets with Python.",
                "dur": "~12 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=NWONeJKn6kc",
            },
        ],
    },
    "🧠 TensorFlow / Deep Learning": {
        "badge": "b-dl",
        "id": "dl",
        "playlists": [
            {
                "title": "TensorFlow 2.0 Complete Course",
                "channel": "freeCodeCamp / Tim Ruscica",
                "desc": "7-hour complete TensorFlow 2.0 course. Neural nets, CNNs, RNNs, NLP. Project-based.",
                "dur": "7 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=tPYj3fFJGjk",
            },
            {
                "title": "Deep Learning with Python (Keras + TF)",
                "channel": "Sentdex (Harrison Kinsley)",
                "desc": "Hands-on deep learning. Builds models step by step. Great for practical understanding of TF/Keras.",
                "dur": "~12 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/playlist?list=PLQVvvaa0QuDfhTox0AjmQ6tvTgMBZBEXN",
            },
            {
                "title": "Neural Networks – 3Blue1Brown",
                "channel": "3Blue1Brown (Grant Sanderson)",
                "desc": "WATCH THIS FIRST. Beautiful visual explanation of how neural networks and backprop actually work. 4 videos.",
                "dur": "1 hr",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
            },
            {
                "title": "Krish Naik – Complete Deep Learning Playlist",
                "channel": "Krish Naik",
                "desc": "Comprehensive DL series from Indian ML educator. ANN, CNN, RNN, LSTM, Transfer Learning.",
                "dur": "~20 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/playlist?list=PLZoTAELRMXVPGU70ZGsckrMdr0FteeRUi",
            },
        ],
    },
    "✨ LangChain / GenAI": {
        "badge": "b-ai",
        "id": "ai",
        "playlists": [
            {
                "title": "Complete LangChain Course for Generative AI",
                "channel": "Krish Naik",
                "desc": "3-hr complete LangChain course. Chatbots, RAG pipelines, API deployment, Groq + HuggingFace integration.",
                "dur": "3 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=swCpkRLFWuQk",
            },
            {
                "title": "LangChain v1 Crash Course – Build Autonomous Agents",
                "channel": "Krish Naik",
                "desc": "Latest LangChain v1. Agents, tools, structured output, Pydantic, streaming, human-in-the-loop.",
                "dur": "2 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=wCpkRLFWuQk",
            },
            {
                "title": "Complete RAG Crash Course with LangChain",
                "channel": "Krish Naik",
                "desc": "2-hour RAG systems from scratch. FAISS, vector DBs, retrieval augmented generation. Directly relevant to VerifAI.",
                "dur": "2 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=sVcwVQRHIc8",
            },
            {
                "title": "Generative AI Full Course 2025",
                "channel": "freeCodeCamp",
                "desc": "Complete GenAI landscape: LLMs, prompt engineering, fine-tuning, agents, RAG, deployment.",
                "dur": "~10 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=mEsleV16qdo",
            },
        ],
    },
    "⚡ FastAPI / Flask": {
        "badge": "b-tool",
        "id": "api",
        "playlists": [
            {
                "title": "FastAPI Tutorial – Complete Beginners Course",
                "channel": "Tech With Tim",
                "desc": "Beginner FastAPI course. CRUD, Pydantic, path params, request bodies. Clean and practical.",
                "dur": "~3 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=CBASjF0dYPU",
            },
            {
                "title": "FastAPI – Full Course (Endpoints to Deployment)",
                "channel": "Amigoscode",
                "desc": "REST APIs with FastAPI, SQLAlchemy, PostgreSQL, deployment. Production-ready patterns.",
                "dur": "~5 hrs",
                "level": "Intermediate",
                "link": "https://www.youtube.com/watch?v=0sOvCWFmrtA",
            },
            {
                "title": "Flask Tutorial Series",
                "channel": "Corey Schafer",
                "desc": "Best Flask series on YouTube. 15 videos covering routes, templates, DB, login, deployment.",
                "dur": "~8 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH",
            },
            {
                "title": "REST API with Python & Flask",
                "channel": "freeCodeCamp",
                "desc": "Build a complete REST API with Flask, authentication, and database from scratch.",
                "dur": "~2 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=GMppyAPbLYk",
            },
        ],
    },
    "☁️ AWS / Cloud": {
        "badge": "b-cloud",
        "id": "cloud",
        "playlists": [
            {
                "title": "AWS Tutorial for Beginners – Full 9hr Course",
                "channel": "freeCodeCamp",
                "desc": "Comprehensive AWS beginner course. EC2, S3, Lambda, networking, security, billing.",
                "dur": "9 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=ulprqHHWlng",
            },
            {
                "title": "AWS Fundamentals – Core Services",
                "channel": "TechWorld with Nana",
                "desc": "2.5-hr straight-to-the-point AWS course. IAM, EC2, S3, CloudFormation. Real-world practical focus.",
                "dur": "2.5 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=ZB5ONbD_SMY",
            },
            {
                "title": "AWS 107-Hour Cloud Project Bootcamp",
                "channel": "freeCodeCamp / Andrew Brown",
                "desc": "Full project bootcamp. Design, build, deploy real AWS cloud project end-to-end.",
                "dur": "107 hrs",
                "level": "Advanced",
                "link": "https://www.youtube.com/watch?v=zA8guDqfv40",
            },
            {
                "title": "Docker Tutorial for Beginners",
                "channel": "TechWorld with Nana",
                "desc": "Essential for cloud deployment. Docker concepts + hands-on. Pairs with FastAPI + AWS deployment.",
                "dur": "3 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/watch?v=3c-iBn73dDE",
            },
        ],
    },
    "📊 Statistics / EDA": {
        "badge": "b-stat",
        "id": "stat",
        "playlists": [
            {
                "title": "Statistics Fundamentals",
                "channel": "StatQuest (Josh Starmer)",
                "desc": "THE best stats playlist. Probability, distributions, hypothesis testing, p-values, correlation. Visual + clear.",
                "dur": "~10 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9",
            },
            {
                "title": "Pandas Data Analysis – Visualization with Seaborn & Matplotlib",
                "channel": "Corey Schafer",
                "desc": "Matplotlib + Seaborn complete tutorials for data visualization. Directly for EDA projects.",
                "dur": "~5 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PL-osiE80TeTvipOqomVEviRg7LUgV14B7",
            },
            {
                "title": "Exploratory Data Analysis – Complete Python EDA",
                "channel": "Krish Naik",
                "desc": "Full EDA workflow in Python: missing values, outliers, feature engineering, visualization, correlation.",
                "dur": "~6 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLZoTAELRMXVPzj1D0i_6ajJ6gyD22b3jh",
            },
            {
                "title": "Data Analyst Bootcamp – Tableau + Power BI",
                "channel": "Alex the Analyst",
                "desc": "Visualization tools: Tableau and Power BI from scratch. Essential for DA roles needing BI dashboards.",
                "dur": "~8 hrs",
                "level": "Beginner",
                "link": "https://www.youtube.com/playlist?list=PLUaB-1hjhk8FE_XZ87vPPSfHqb6OcM0cF",
            },
        ],
    },
    "🎓 Free Certifications": {
        "badge": "b-cert",
        "id": "cert",
        "playlists": [
            {
                "title": "Claude 101",
                "channel": "Anthropic Academy",
                "desc": "Phase 1 · Basics, core features, everyday workflows. Quick start — complete first.",
                "dur": "~0.5 hr",
                "level": "Beginner",
                "link": "https://anthropic.skilljar.com/claude-101",
            },
            {
                "title": "AI Fluency: Framework & Foundations",
                "channel": "Anthropic Academy",
                "desc": "Phase 1 · 4D AI framework, responsible AI, collaboration. Strong resume base for any AI/ML role.",
                "dur": "~1 hr",
                "level": "Beginner",
                "link": "https://anthropic.skilljar.com/ai-fluency",
            },
            {
                "title": "Building with the Claude API",
                "channel": "Anthropic Academy",
                "desc": "Phase 2 · System prompts, tool use, RAG, production patterns. 8+ hrs hands-on.",
                "dur": "8+ hrs",
                "level": "Intermediate",
                "link": "https://anthropic.skilljar.com/generative-ai-api-development",
            },
            {
                "title": "Claude Code in Action",
                "channel": "Anthropic Academy",
                "desc": "Phase 2 · Context handling, tool chaining, MCP in Claude Code. Trending skill in 2026.",
                "dur": "~2 hrs",
                "level": "Intermediate",
                "link": "https://anthropic.skilljar.com/claude-code-in-action",
            },
            {
                "title": "Introduction to Model Context Protocol (MCP)",
                "channel": "Anthropic Academy",
                "desc": "Phase 3 · MCP servers, clients, tools, resources. Do before Advanced MCP.",
                "dur": "~2 hrs",
                "level": "Intermediate",
                "link": "https://anthropic.skilljar.com/introduction-to-mcp",
            },
            {
                "title": "Advanced Model Context Protocol (MCP)",
                "channel": "Anthropic Academy",
                "desc": "Phase 3 · Sampling, file access, production deployment. Rare skill — few freshers have it.",
                "dur": "~2 hrs",
                "level": "Advanced",
                "link": "https://anthropic.skilljar.com/advanced-mcp",
            },
            {
                "title": "Introduction to Agent Skills",
                "channel": "Anthropic Academy",
                "desc": "Phase 3 · Autonomous agents, tool use, decision loops. Cutting-edge AI territory.",
                "dur": "~2 hrs",
                "level": "Advanced",
                "link": "https://anthropic.skilljar.com/introduction-to-agent-skills",
            },
            {
                "title": "Claude on AWS Bedrock",
                "channel": "Anthropic Academy",
                "desc": "Phase 4 · Enterprise deployment on AWS. Useful for cloud-heavy roles.",
                "dur": "~1 hr",
                "level": "Intermediate",
                "link": "https://anthropic.skilljar.com/claude-on-aws-bedrock",
            },
            {
                "title": "Claude on Google Vertex AI",
                "channel": "Anthropic Academy",
                "desc": "Phase 4 · GCP integration patterns. Pairs well with your AWS knowledge.",
                "dur": "~1 hr",
                "level": "Intermediate",
                "link": "https://anthropic.skilljar.com/claude-on-google-vertex-ai",
            },
            {
                "title": "Generative AI Explained",
                "channel": "NVIDIA DLI",
                "desc": "NVIDIA · Quick conceptual cert. GenAI landscape, LLMs, diffusion models.",
                "dur": "~1 hr",
                "level": "Beginner",
                "link": "https://courses.nvidia.com/courses/course-v1:DLI+S-FX-07+V1",
            },
            {
                "title": "Getting Started with Deep Learning",
                "channel": "NVIDIA DLI",
                "desc": "NVIDIA · Neural nets, CNNs, data augmentation using TensorFlow/Keras. GPU labs on NVIDIA cloud.",
                "dur": "~8 hrs",
                "level": "Intermediate",
                "link": "https://courses.nvidia.com/courses/course-v1:DLI+C-FX-01+V1",
            },
            {
                "title": "Building RAG Agents with LLMs",
                "channel": "NVIDIA DLI",
                "desc": "NVIDIA · RAG from prototype to production. Directly complements your VerifAI/FAISS work.",
                "dur": "~8 hrs",
                "level": "Advanced",
                "link": "https://courses.nvidia.com/courses/course-v1:DLI+S-FX-15+V1",
            },
            {
                "title": "Fundamentals of Accelerated Computing with CUDA Python",
                "channel": "NVIDIA DLI",
                "desc": "NVIDIA · Accelerate Python using CUDA + Numba. Rare skill that stands out on a data science resume.",
                "dur": "~3 hrs",
                "level": "Advanced",
                "link": "https://courses.nvidia.com/courses/course-v1:DLI+C-AC-02+V1",
            },
        ],
    },
}

TOTAL_PLAYLISTS = sum(len(v["playlists"]) for v in SKILLS.values())

ROADMAP = [
    {
        "week": "Week 1-2",
        "title": "Foundation Refresh",
        "items": [
            "Python for Data Science (Corey Schafer)",
            "Pandas & NumPy (Data School)",
            "SQL Basics → Advanced (Alex the Analyst)",
            "Build: EDA project on Kaggle dataset",
        ],
    },
    {
        "week": "Week 3-4",
        "title": "ML Core Skills",
        "items": [
            "Scikit-Learn full playlist (Data School)",
            "StatQuest Statistics Fundamentals",
            "ML with Python (Codebasics)",
            "Build: Customer Churn model",
        ],
    },
    {
        "week": "Week 5-6",
        "title": "Deep Learning + APIs",
        "items": [
            "TensorFlow/Keras (Sentdex / freeCodeCamp)",
            "FastAPI complete course (Tech With Tim)",
            "Flask tutorials (Corey Schafer)",
            "Build: ML model served as FastAPI endpoint",
        ],
    },
    {
        "week": "Week 7-8",
        "title": "GenAI + Cloud Deploy",
        "items": [
            "LangChain complete (Krish Naik)",
            "RAG pipeline + Agents (Krish Naik)",
            "AWS basics (freeCodeCamp / TechWorld Nana)",
            "Build: Deploy on AWS / Oracle Cloud",
        ],
    },
]

JOB_TARGETS = [
    {
        "company": "Google",
        "role": "Data Analyst / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://careers.google.com",
    },
    {
        "company": "Microsoft",
        "role": "Data Scientist / AI Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://careers.microsoft.com",
    },
    {
        "company": "Amazon",
        "role": "Data Scientist / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://amazon.jobs",
    },
    {
        "company": "Meta",
        "role": "Data Analyst / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.metacareers.com",
    },
    {
        "company": "Apple",
        "role": "ML Engineer / Data Scientist",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.apple.com/jobs/us/",
    },
    {
        "company": "Netflix",
        "role": "Data Engineer / ML Engineer",
        "sector": "Media",
        "priority": "High",
        "link": "https://jobs.netflix.com",
    },
    {
        "company": "Spotify",
        "role": "Data Scientist / ML Engineer",
        "sector": "Media",
        "priority": "Medium",
        "link": "https://www.lifeatspotify.com",
    },
    {
        "company": "Uber",
        "role": "Data Scientist / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.uber.com/us/en/careers/",
    },
    {
        "company": "Airbnb",
        "role": "Data Scientist / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.airbnb.com/careers",
    },
    {
        "company": "LinkedIn",
        "role": "Data Scientist / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.linkedin.com/careers",
    },
    {
        "company": "Salesforce",
        "role": "Data Analyst / ML Engineer",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.salesforce.com/company/careers/",
    },
    {
        "company": "Adobe",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.adobe.com/careers.html",
    },
    {
        "company": "Oracle",
        "role": "Data Analyst / ML Engineer",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.oracle.com/careers/",
    },
    {
        "company": "IBM",
        "role": "Data Scientist / AI Engineer",
        "sector": "Tech",
        "priority": "Medium",
        "link": "https://www.ibm.com/careers/us-en/",
    },
    {
        "company": "Intel",
        "role": "ML Engineer / Data Scientist",
        "sector": "Hardware",
        "priority": "Medium",
        "link": "https://jobs.intel.com",
    },
    {
        "company": "NVIDIA",
        "role": "Deep Learning Engineer",
        "sector": "Hardware",
        "priority": "High",
        "link": "https://www.nvidia.com/en-us/careers/",
    },
    {
        "company": "Palantir",
        "role": "Data Engineer / ML Engineer",
        "sector": "Tech",
        "priority": "High",
        "link": "https://www.palantir.com/careers/",
    },
    {
        "company": "Snowflake",
        "role": "Data Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.snowflake.com/careers/",
    },
    {
        "company": "Databricks",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.databricks.com/careers",
    },
    {
        "company": "Cloudera",
        "role": "Data Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "Low",
        "link": "https://www.cloudera.com/about/careers.html",
    },
    {
        "company": "DataRobot",
        "role": "ML Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.datarobot.com/careers/",
    },
    {
        "company": "Alteryx",
        "role": "Data Analyst / ML Engineer",
        "sector": "SaaS",
        "priority": "Low",
        "link": "https://www.alteryx.com/company/careers",
    },
    {
        "company": "Qlik",
        "role": "Data Analyst",
        "sector": "SaaS",
        "priority": "Low",
        "link": "https://www.qlik.com/us/company/careers",
    },
    {
        "company": "Workday",
        "role": "Data Scientist",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.workday.com/en-us/company/careers.html",
    },
    {
        "company": "ServiceNow",
        "role": "ML Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.servicenow.com/careers",
    },
    {
        "company": "Atlassian",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.atlassian.com/careers",
    },
]

LOW_COMPETITION = [
    {
        "company": "H2O.ai",
        "role": "ML Engineer / Data Scientist",
        "sector": "AI/ML SaaS",
        "priority": "High",
        "link": "https://www.h2o.ai/company/careers/",
        "comp": "LOW",
    },
    {
        "company": "Dataiku",
        "role": "Data Scientist / ML Engineer",
        "sector": "AI/ML SaaS",
        "priority": "High",
        "link": "https://www.dataiku.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "Scale AI",
        "role": "ML Engineer / Data Analyst",
        "sector": "AI/ML SaaS",
        "priority": "High",
        "link": "https://scale.com/careers",
        "comp": "LOW",
    },
    {
        "company": "C3.ai",
        "role": "Data Scientist / ML Engineer",
        "sector": "AI/ML SaaS",
        "priority": "High",
        "link": "https://www.c3.ai/careers/",
        "comp": "LOW",
    },
    {
        "company": "Databricks",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.databricks.com/careers",
        "comp": "MED",
    },
    {
        "company": "Snowflake",
        "role": "Data Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.snowflake.com/careers/",
        "comp": "MED",
    },
    {
        "company": "Alteryx",
        "role": "Data Analyst / ML Engineer",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.alteryx.com/company/careers",
        "comp": "LOW",
    },
    {
        "company": "Qlik",
        "role": "Data Analyst",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.qlik.com/us/company/careers",
        "comp": "LOW",
    },
    {
        "company": "Trifacta (Google)",
        "role": "Data Engineer / Analyst",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.trifacta.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "ThoughtSpot",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.thoughtspot.com/careers",
        "comp": "LOW",
    },
    {
        "company": "Fivetran",
        "role": "Data Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.fivetran.com/careers",
        "comp": "LOW",
    },
    {
        "company": "Monte Carlo",
        "role": "Data Engineer / Analyst",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.montecarlodata.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "dbt Labs",
        "role": "Data Engineer / Analyst",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.getdbt.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "HashiCorp",
        "role": "Data Engineer / SRE",
        "sector": "DevOps/SaaS",
        "priority": "Medium",
        "link": "https://www.hashicorp.com/careers",
        "comp": "LOW",
    },
    {
        "company": "Confluent",
        "role": "Data Engineer / Platform Engineer",
        "sector": "SaaS",
        "priority": "High",
        "link": "https://www.confluent.io/careers/",
        "comp": "LOW",
    },
    {
        "company": "Elastic",
        "role": "ML Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.elastic.co/careers",
        "comp": "LOW",
    },
    {
        "company": "MongoDB",
        "role": "Data Engineer / Data Scientist",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.mongodb.com/company/careers",
        "comp": "MED",
    },
    {
        "company": "Neo4j",
        "role": "Data Scientist / ML Engineer",
        "sector": "SaaS",
        "priority": "Medium",
        "link": "https://www.neo4j.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "RapidMiner",
        "role": "Data Scientist / ML Engineer",
        "sector": "AI/ML SaaS",
        "priority": "Low",
        "link": "https://www.rapidminer.com/careers/",
        "comp": "LOW",
    },
    {
        "company": "HPE",
        "role": "Data Engineer / ML Engineer",
        "sector": "Enterprise",
        "priority": "Low",
        "link": "https://www.hpe.com/us/en/careers.html",
        "comp": "LOW",
    },
    {
        "company": "Teradata",
        "role": "Data Analyst / Data Engineer",
        "sector": "Enterprise",
        "priority": "Low",
        "link": "https://www.teradata.com/careers",
        "comp": "LOW",
    },
    {
        "company": "SAP",
        "role": "Data Scientist / ML Engineer",
        "sector": "Enterprise",
        "priority": "Medium",
        "link": "https://www.sap.com/about/careers.html",
        "comp": "MED",
    },
    {
        "company": "Informatica",
        "role": "Data Engineer / Data Analyst",
        "sector": "Enterprise",
        "priority": "Low",
        "link": "https://www.informatica.com/about-us/careers.html",
        "comp": "LOW",
    },
]
